### PR TITLE
Fix exit code and issue with build

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Comment by bbockelm** [comment]
@vkuznet - the exit codes patch looks good.  What symbols are missing that require the GLIBCXX ABI change?  Sounds more like it's missing being linked to a given library.

**Comment by vkuznet** [comment]
The GLIBCXX issue pop-up if I make a build using cmsweb gcc which is 6.3.0 and then use libSimpleProxyUtils.so in apache which look-up symbols from system libstd++ which are compiled with system gcc 4.8.5. 

The issue was discussed here:
https://stackoverflow.com/questions/45417707/glibcxx-use-cxx11-abi-gcc-4-8-and-abi-compatibility

But now I was able to not use cmsweb gcc, so we are good without `-D_GLIBCXX_USE_CXX11_ABI=0"` flag. Therefore I'll reverse this change in a minute.

**Comment by vkuznet** [comment]
I reversed the flag usage. Please review, merge and more importantly tag the code that I can use a tag in a spec file to make a build.

**Comment by bbockelm** [comment]
@vkuznet - tagged as v0.1.1

**Pull request merged**
